name: meeting-mind-ai

services:
  postgres:
    image: postgres:16
    container_name: meetingmind-postgres

    environment:
      POSTGRES_DB: meetingmind
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d meetingmind" ]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:9.5
    container_name: meetingmind-pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

    ports:
      - "5050:80"

    depends_on:
      - postgres

    restart: always

    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin_data: