spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:meetingmind}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    org.hibernate.SQL: debug

app:
  cors:
    allowed-origin: ${FRONTEND_URL:http://localhost:5173}