spring:
  application:
    name: meeting-mind-ai

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  ai:
    google:
      genai:
        project-id: ${PROJECT_ID}
        api-key: ${GEMINI_API_KEY}
        chat:
          model: gemini-3.1-flash-lite

app:
  file:
    upload-dir: uploads/meetings
    max-size: 10485760 # 10MB
    allowed-types:
      # PDF
      - application/pdf

      # Microsoft Word
      - application/vnd.openxmlformats-officedocument.wordprocessingml.document
      - application/msword

      # Plain Text
      - text/plain

      # Markdown
      - text/markdown
      - text/x-markdown

      # Rich Text
      - application/rtf
      - text/rtf

      # OpenDocument
      - application/vnd.oasis.opendocument.text

      # HTML
      - text/html

    allowed-extensions:
      - pdf
      - doc
      - docx
      - txt
      - md
      - rtf
      - odt
      - html
      - htm

  ai:
    providers:
      gemini:
        models:
          - gemini-3.1-flash-lite
          - gemini-3.1-flash-lite-preview
          - gemini-3.5-flash
          - gemini-3.5-flash-lite
          - gemini-3.6-flash
          - gemini-3.1-pro-preview
          - gemini-3-pro-preview
