spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meetingmind_test
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: false

logging:
  level:
    root: WARN